//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LSCrypt.rc
//
#include "Version.h"
#define IDCANCEL2                       3
#define IDS_PROJNAME                    100
#define IDR_UFCRYPT                     101
#define IDS_MENU_ENCRYPT_CH             101
#define IDR_LSCRYPTSHELLEXT             102
#define IDS_MENU_ENCRYPT_EN             102
#define IDS_MENU_DECRYPT_CH             103
#define IDS_MENU_DECRYPT_EN             104
#define IDS_MENU_ABOUT_CH               105
#define IDS_MENU_ABOUT_EN               106
#define IDS_DLG_ABOUT_TITLE_EN          107
#define IDS_DLG_ABOUT_TITLE_CH          108
#define IDS_DLG_ABOUT_BUTN_OK_EN        109
#define IDS_DLG_REG_INVALID_SERINAL_EN  110
#define IDS_DLG_REG_INVALID_SERINAL_CH  111
#define IDS_DLG_PWD_EMPTY_PWD_EN        112
#define IDS_DLG_PWD_EMPTY_PWD_CH        113
#define IDS_DLG_PWD_NOTMATCH_PWD_EN     114
#define IDS_DLG_PWD_NOTMATCH_PWD_CH     115
#define IDS_DLG_PWD_INPUT_PWD_EN        116
#define IDS_DLG_PWD_INPUT_PWD_CH        117
#define IDS_DLG_MAIN_FILE_NOTEXIST_EN   118
#define IDS_DLG_MAIN_FILE_NOTEXIST_CH   119
#define IDS_DLG_MAIN_DECRYPT_ERROR_EN   120
#define IDS_DLG_MAIN_DECRYPT_ERROR_CH   121
#define IDS_DLG_PWD_TIP_DE_CH           122
#define IDS_DLG_PWD_TIP_DE_EN           123
#define IDS_DLG_PWD_TIP_EN_CH           124
#define IDS_DLG_PWD_TIP_EN_EN           125
#define IDS_DLG_REG_TIMES_EN            126
#define IDS_DLG_REG_TIMES_CH            127
#define IDS_DLG_REG_TRY_EN              128
#define IDS_DLG_REG_TRY_CH              129
#define IDS_DLG_REG_REG_EN              130
#define IDS_DLG_REG_REG_CH              131
#define IDS_DLG_REG_QUIT_EN             132
#define IDS_DLG_REG_QUIT_CH             133
#define IDS_DLG_REG_EXPIRED_EN          134
#define IDS_DLG_REG_EXPIRED_CH          135
#define IDD_PROGRESS                    201
#define IDC_PROGRESS_CURRENT            201
#define IDC_PROGRESS_TOTAL              202
#define IDI_CRYPT                       203
#define IDC_STATIC_CURRENT_FILE         203
#define IDC_STATIC_DONE_TOTAL           204
#define IDB_SHELLEXT                    204
#define IDB_SHELLEXT_EN                 205
#define IDD_PASSWORD                    205
#define IDC_PASSWORD1                   205
#define IDB_SHELLEXT_DE                 206
#define IDC_PASSWORD2                   206
#define IDD_DIALOG1                     206
#define IDD_ABOUT                       206
#define IDD_INPUTSERINAL                207
#define IDS_DLG_ABOUT_BUTN_OK_CH        208
#define IDC_STATIC_PASSWORD             209
#define IDS_DLG_ABOUT_STATIC_REG_EN     209
#define IDC_MY_HAND                     209
#define IDC_STATIC_PASSWORD_CONFIRM     210
#define IDS_DLG_ABOUT_STATIC_REG_CH     210
#define IDC_EDIT_SN1                    211
#define IDS_DLG_ABOUT_STATIC_UNREG_EN   211
#define IDD_REGISTRY                    211
#define IDC_EDIT_SN2                    212
#define IDS_DLG_ABOUT_STATIC_UNREG_CH   212
#define IDC_EDIT_SN3                    213
#define IDS_DLG_ABOUT_HYPERLINK_REG_EN  213
#define IDB_LOGO                        213
#define IDC_EDIT_SN4                    214
#define IDS_DLG_ABOUT_HYPERLINK_REG_CH  214
#define IDD_DIALOG2                     214
#define IDD_PROGRESS_SINGLE             214
#define IDC_EDIT_SN5                    215
#define IDS_DLG_PROGRESS_STATIC1_EN     215
#define IDC_STATIC_TEXT                 216
#define IDS_DLG_PROGRESS_STATIC1_CH     216
#define IDC_STATIC_INFO                 217
#define IDS_DLG_PROGRESS_STATIC_CURRENT_PROGRESS_EN 217
#define IDC_STATIC1                     218
#define IDS_DLG_PROGRESS_STATIC_CURRENT_PROGRESS_CH 218
#define IDS_DLG_PROGRESS_STATIC_TOTAL_PROGRESS_EN 219
#define IDC_STATIC_CURRENT_PROGRESS     219
#define IDS_DLG_PROGRESS_STATIC_TOTAL_PROGRESS_CH 220
#define IDC_STATIC_TOTAL_PROGRESS       220
#define IDS_DLG_PROGRESS_BUTN_CANCEL_EN 221
#define IDC_STATIC_DISPLAY              221
#define IDS_DLG_PROGRESS_BUTN_CANCEL_CH 222
#define IDC_LOGO                        222
#define IDS_DLG_PWD_STATIC1_EN          223
#define IDC_TIP                         223
#define IDS_DLG_PWD_STATIC1_CH          224
#define IDC_ICON                        224
#define IDS_DLG_PWD_STATIC2_EN          225
#define IDC_PROGRESS1                   225
#define IDC_PROGRESS_SINGLE             225
#define IDS_DLG_PWD_STATIC2_CH          226
#define IDC_ERR_TEXT                    226
#define IDS_DLG_PWD_BUTN_OK_EN          227
#define IDS_DLG_PWD_BUTN_OK_CH          228
#define IDS_DLG_PWD_BUTN_CANCEL_EN      229
#define IDS_DLG_PWD_BUTN_CANCEL_CH      230
#define IDS_DLG_PWD_TITLE_EN            231
#define IDS_DLG_PWD_TITLE_CH            232
#define IDS_DLG_REG_TITLE_EN            233
#define IDS_DLG_REG_TITLE_CH            234
#define IDS_DLG_REG_STATIC_TEXT_EN      235
#define IDS_DLG_REG_STATIC_TEXT_CH      236
#define IDS_DLG_REG_BUTN_OK_EN          237
#define IDS_DLG_REG_BUTN_OK_CH          238
#define IDS_DLG_REG_BUTN_CANCEL_EN      239
#define IDS_DLG_REG_BUTN_CANCEL_CH      240
#define IDS_DLG_REG_HYPERLINK_GETSERINAL_EN 241
#define IDS_DLG_REG_HYPERLINK_GETSERINAL_CH 242
#define IDS_DLG_REG_EMPTY_SERINAL_EN    243
#define IDS_DLG_REG_EMPTY_SERINAL_CH    244
#define IDS_DLG_REG_SUCCEFULLY_EN       245
#define IDS_DLG_REG_SUCCEFULLY_CH       246
#define IDS_DLG_MAIN_EXIT_EN            247
#define IDS_DLG_MAIN_EXIT_CH            248
#define IDC_INPUT_SERINAL               250

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        215
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         227
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
